Repository ethereum-optimism/op-reth, pull requests merged in 2025-01, with the labels that each got.

#17 chore(ci): strip CI to op-reth testing essentials
  .github/assets/hive/Dockerfile
  .github/assets/hive/build_simulators.sh
  .github/assets/hive/expected_failures.yaml
  .github/assets/hive/load_images.sh
  .github/assets/hive/no_sim_build.diff
  .github/assets/hive/parse.py
  .github/assets/hive/run_simulator.sh
  .github/assets/kurtosis_network_params.yaml
  .github/assets/label_pr.js
  .github/workflows/bench.yml
  .github/workflows/book.yml
  .github/workflows/compact.yml
  .github/workflows/dependencies.yml
  .github/workflows/docker-git.yml
  .github/workflows/docker.yml
  .github/workflows/hive.yml
  .github/workflows/integration.yml
  .github/workflows/kurtosis-op.yml
  .github/workflows/kurtosis.yml
  .github/workflows/label-pr.yml
  .github/workflows/lint.yml
  .github/workflows/prepare-reth.yml
  .github/workflows/release-dist.yml
  .github/workflows/release.yml
  .github/workflows/stage.yml
  .github/workflows/sync.yml
  .github/workflows/unit.yml
  .github/workflows/windows.yml
Labels: meta

#23 feat(isthmus): Pre-req verify storage root in pipeline sync [upstreaming]
  Cargo.lock
  bin/reth/src/commands/debug_cmd/build_block.rs
  bin/reth/src/commands/debug_cmd/in_memory_merkle.rs
  bin/reth/src/commands/debug_cmd/merkle.rs
  crates/blockchain-tree/Cargo.toml
  crates/blockchain-tree/src/chain.rs
  crates/engine/tree/Cargo.toml
  crates/engine/tree/src/tree/mod.rs
  crates/ethereum/evm/Cargo.toml
  crates/ethereum/evm/src/execute.rs
  crates/evm/Cargo.toml
  crates/evm/src/either.rs
  crates/evm/src/execute.rs
  crates/evm/src/metrics.rs
  crates/evm/src/noop.rs
  crates/evm/src/test_utils.rs
  crates/exex/exex/Cargo.toml
  crates/exex/exex/src/backfill/job.rs
  crates/exex/exex/src/backfill/test_utils.rs
  crates/optimism/evm/Cargo.toml
  crates/optimism/evm/src/execute.rs
  crates/primitives-traits/src/account.rs
  crates/revm/Cargo.toml
  crates/revm/src/cached.rs
  crates/revm/src/database.rs
  crates/revm/src/lib.rs
  crates/rpc/rpc/src/debug.rs
  crates/rpc/rpc/src/validation.rs
  crates/stages/stages/Cargo.toml
  crates/stages/stages/src/stages/execution.rs
  examples/custom-beacon-withdrawals/src/main.rs
Labels: B-isthmus-devnet-0, A-execution

#26 fix(docs): revert overwrite pull #24
  README.md
Labels: bug, documentation

#29 feat(ci): Add kurtosis config without op-geth
  .github/assets/kurtosis_op_network_params_local_no_op_geth.yaml
  .github/assets/kurtosis_op_network_params_remote_no_op_geth.yaml
  .github/workflows/kurtosis-op-local-no-op-geth.yml
  .github/workflows/kurtosis-op-remote-no-op-geth.yml
Labels: meta

#32 feat(ci): Speed up building op-reth in kurtosis workflow
  Cargo.toml
Labels: meta

#33 fix(ci): fix up #32, disable build optimisations for op-reth in kurtosis
  Cargo.toml
Labels: meta

#31 feat(ci): Enable isthmus time at genesis
  .github/assets/kurtosis_op_network_params_local.yaml
  .github/assets/kurtosis_op_network_params_local_no_op_geth.yaml
Labels: meta

#47 fix(optimism): Node Tests
  Cargo.lock
  crates/engine/tree/src/tree/mod.rs
  crates/net/network/benches/broadcast.rs
  crates/net/network/benches/tx_manager_hash_fetching.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/net/network/tests/it/multiplex.rs
  crates/net/network/tests/it/requests.rs
  crates/net/network/tests/it/transaction_hash_fetching.rs
  crates/net/network/tests/it/txgossip.rs
  crates/optimism/node/src/txpool.rs
  crates/prune/prune/Cargo.toml
  crates/prune/prune/src/segments/mod.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/validate/eth.rs
Labels: A-tx-pool

#50 chore(meta): Add blank pr template
  .github/pull_request_template.md
Labels: meta

#56 Compute withdrawals root in execution payload validation
  Cargo.lock
  crates/e2e-test-utils/src/lib.rs
  crates/ethereum/node/tests/e2e/utils.rs
  crates/node/api/src/node.rs
  crates/node/builder/src/builder/mod.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/engine.rs
  crates/optimism/node/src/node.rs
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/lib.rs
  crates/optimism/payload/src/validator.rs
Labels: D-isthmus-devnet, A-consensus

#19 feat(isthmus): verify storage root in execution
  Cargo.lock
  crates/consensus/consensus/src/lib.rs
  crates/e2e-test-utils/src/lib.rs
  crates/ethereum/node/tests/e2e/utils.rs
  crates/exex/exex/src/context.rs
  crates/exex/exex/src/dyn_context.rs
  crates/node/api/src/node.rs
  crates/node/builder/src/builder/mod.rs
  crates/optimism/chainspec/Cargo.toml
  crates/optimism/consensus/Cargo.toml
  crates/optimism/consensus/src/error.rs
  crates/optimism/consensus/src/lib.rs
  crates/optimism/consensus/src/validation/canyon.rs
  crates/optimism/consensus/src/validation/isthmus.rs
  crates/optimism/consensus/src/validation/mod.rs
  crates/optimism/evm/src/error.rs
  crates/optimism/evm/src/execute.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/engine.rs
  crates/optimism/node/src/node.rs
  crates/optimism/payload/Cargo.toml
  crates/optimism/payload/src/lib.rs
  crates/optimism/payload/src/validator.rs
  crates/storage/errors/src/provider.rs
  crates/storage/storage-api/src/trie.rs
  crates/trie/sparse/src/trie.rs
  examples/custom-beacon-withdrawals/src/main.rs
Labels: D-isthmus-devnet, A-consensus, A-execution, upstream

#60 feat(l2-withdrawals): withdrawals root in block building
  crates/optimism/payload/src/builder.rs
Labels: D-isthmus-devnet, A-block-building

#35 feat(optimism): Interop Transaction Pool Validation
  Cargo.lock
  Cargo.toml
  crates/engine/tree/src/tree/mod.rs
  crates/net/network/benches/broadcast.rs
  crates/net/network/benches/tx_manager_hash_fetching.rs
  crates/net/network/tests/it/big_pooled_txs_req.rs
  crates/net/network/tests/it/multiplex.rs
  crates/net/network/tests/it/requests.rs
  crates/net/network/tests/it/transaction_hash_fetching.rs
  crates/net/network/tests/it/txgossip.rs
  crates/optimism/node/Cargo.toml
  crates/optimism/node/src/args.rs
  crates/optimism/node/src/engine.rs
  crates/optimism/node/src/node.rs
  crates/optimism/node/src/txpool.rs
  crates/prune/prune/Cargo.toml
  crates/prune/prune/src/segments/mod.rs
  crates/rpc/rpc-engine-api/src/engine_api.rs
  crates/rpc/rpc/src/eth/core.rs
  crates/rpc/rpc/src/eth/helpers/state.rs
  crates/storage/provider/src/test_utils/mock.rs
  crates/transaction-pool/Cargo.toml
  crates/transaction-pool/src/maintain.rs
  crates/transaction-pool/src/validate/eth.rs
  crates/transaction-pool/src/validate/mod.rs
Labels: A-tx-pool, D-interop-devnet

#63 chore(ci): Rename kurtosis workflow file
  .github/workflows/kurtosis-op.yml
Labels: meta
